baseURL = 'https://LearnCIOT.github.io/'
languageCode = "zh-tw"
defaultContentLanguage = "zh-tw"
title = 'Learn CIoT'
theme = "relearn"
metaDataFormat = "yaml"
# required for official documentation served from subfolder
relativeURLs = false
defaultContentLanguageInSubdir= false

[Params]
  editURL = "https://github.com/LearnCIOT/LearnCIOT.github.io/tree/main/content/"
  description = "CIoT Open Data Application - Documentation/Learning Project"
  author = "Ling-Jyh Chen"
  showVisitedLinks = true
  #collapsibleMenu = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableSeoHiddenPages = true
  disableMermaid = false
  #customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"
[Params.socialshare]
  facebook = true
  linkedin = true
  twitter = true
  whatsapp = true
  email = true

[taxonomies]
  category = "categories"
  tag = "tags"
  level = "levels"
  author = "author"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  #section = ["HTML", "RSS" ]
  #page = ["HTML", "RSS"]

[Languages]
[Languages.en]
title = "Tutorial for CIoT Open Data Applications"
weight = 1
languageName = "English"
landingPageURL = "/"
landingPageName = "<i class='fas fa-home'></i> Home"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/LearnCIOT/LearnCIOT.github.io"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Showcases"
url = "showcase"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30

[Languages.zh-tw]
title = "Tutorial for CIoT Open Data Applications"
weight = 2
languageName = "中文"
landingPageURL = "/"
landingPageName = "<i class='fas fa-home'></i> 首頁"

[[Languages.zh-tw.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub"
identifier = "ds"
url = "https://github.com/LearnCIOT/LearnCIOT.github.io"
weight = 10

[[Languages.zh-tw.menu.shortcuts]]
name = "<i class='fas fa-fw fa-heartbeat'></i> 按照難度等級查詢"
url = "levels/"
weight = 100

[[Languages.zh-tw.menu.shortcuts]]
name = "<i class='fas fa-fw fa-tags'></i> 按照文章標籤查詢"
url = "tags/"
weight = 110

[[Languages.zh-tw.menu.shortcuts]]
name = "<i class='fas fa-fw fa-users'></i> 按照文章作者查詢"
url = "author/"
weight = 120

